#!/bin/bash

echo " Tidy Go modules..."

go mod tidy

echo "Linting code with golangci-lint..."
golangci-lint run --config .golangci.yml

# Stage all changes (including go.mod and go.sum) for commit
git add .

echo "Running tests..."

# Generate mocks before running tests
make gen-mock
# Run all tests and ensure they pass before allowing commit
make test
echo "All tests passed!"